version: "3.9"

services:
  pizza-service:
    image: pizza-service:latest
    ports:
      - "9090:8080"
    volumes:
      - ./pizza-service-data:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pizza-service
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
